# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubtella}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mateusz Zawisza"]
  s.date = %q{2010-01-10}
  s.description = %q{Library for Gnuttale in Ruby}
  s.email = %q{mateusz.zawisza@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "README",
     "VERSION",
     "config/config.rb",
     "lib/errors.rb",
     "lib/http_data.rb",
     "lib/logger.rb",
     "lib/peer.rb",
     "lib/rubtella.rb",
     "lib/tcp_data.rb",
     "rubtella.rb",
     "rubtellad.rb"
  ]
  s.homepage = %q{http://github.com/mateuszzawisza/rubtella/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Library for Gnuttale in Ruby}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

